Repository livepeer/pipelines, pull requests merged in 2025-06, with the labels that each got.

#735 feat: add a fishtank demo
  .github/workflows/deploy.fishtank.yml
  .github/workflows/deploy.restreamers.staging.yml
  apps/fishtank/Dockerfile
  apps/fishtank/entrypoint.sh
  apps/fishtank/fly.toml
Labels: Review effort 2/5

#758 Add effect to highlight input box on Trending prompt click
  apps/app/components/home/PromptForm.tsx
  apps/app/components/home/PromptPanel.tsx
  apps/app/tailwind.config.ts
Labels: Review effort 2/5

#753 box: Add local box run
  apps/app/.env.example
  apps/app/components/welcome/featured/BentoGridOverlay.tsx
  apps/app/components/welcome/featured/MainContent.tsx
  apps/app/lib/serverEnv.ts
Labels: Review effort 3/5

#748 Standalone Prompt Queue
  .github/workflows/deploy.api.staging.yml
  apps/api/.gitignore
  apps/api/Cargo.lock
  apps/api/Cargo.toml
  apps/api/Dockerfile
  apps/api/fly.toml
  apps/api/src/config.rs
  apps/api/src/handlers/api.rs
  apps/api/src/handlers/mod.rs
  apps/api/src/handlers/ws.rs
  apps/api/src/main.rs
  apps/api/src/models.rs
  apps/api/src/services/mod.rs
  apps/api/src/services/prompt_manager.rs
  apps/api/src/services/redis.rs
  apps/api/src/services/stream_api.rs
  apps/api/src/state.rs
  apps/app/app/(main)/MultiplayerHomepage.tsx
  apps/app/app/PromptPanel.tsx
  apps/app/app/api/cron/process-queue/route.ts
  apps/app/app/api/prompts/route.ts
  apps/app/app/api/prompts/store.ts
  apps/app/app/api/prompts/types.ts
  apps/app/app/hooks/usePromptQueue.ts
  apps/app/components/home/Footer.tsx
  apps/app/components/home/HeaderSection.tsx
  apps/app/components/home/HeroSection.tsx
  apps/app/components/home/PromptDisplay.tsx
  apps/app/components/home/PromptForm.tsx
  apps/app/components/home/PromptPanel.tsx
  apps/app/hooks/usePromptsApi.ts
  apps/app/hooks/useRandomPromptApiTimer.ts
  apps/app/lib/db/services/prompt-queue.ts
  apps/app/vercel.json
  docker-compose.dev.yaml
  mprocs.yaml
Labels: Review effort 4/5

#765 feat: remove random prompts
  apps/api/src/services/prompt_manager.rs
  apps/app/app/hooks/usePromptQueue.ts
Labels: Review effort 2/5

#770 dd: feat: clear cache on mismatched pipeline id
  apps/app/components/welcome/featured/Dreamshaper.tsx
  apps/app/hooks/useDreamshaper.tsx
Labels: Review effort 3/5

#775 Multiplayer: Move Trending box down to be just above input box
  apps/app/app/PromptPanel.tsx
Labels: Review effort 3/5
