Repository livepeer/pipelines, pull requests merged in 2025-05, with the labels that each got.

#537 ci: add pr agent
  .github/workflows/pr-agent.yml
Labels: Review effort 2/5

#540 feat: order clips by remix counts
  apps/app/app/(main)/layout.tsx
  apps/app/app/api/clips/route.ts
Labels: Review effort 2/5

#541 feat: migrate on build
  apps/app/drizzle/0009_ambitious_skin.sql
  apps/app/drizzle/meta/0009_snapshot.json
  apps/app/drizzle/meta/_journal.json
  apps/app/lib/db/schema.ts
  apps/app/package.json
Labels: Review effort 2/5

#547 fix: z-index based errors causing capacity screen overlay everywhere
  apps/app/components/welcome/featured/InputPrompt.tsx
  apps/app/components/welcome/featured/PlayerOverlay.tsx
  packages/design-system/components/ui/dialog.tsx
Labels: Review effort 2/5

#549 fix: hero text lost on back navigation from quickvideo
  apps/app/app/(main)/QuickviewVideo.tsx
Labels: Review effort 2/5

#553 fix: shared urls overriden by older inputPrompts
  apps/app/components/welcome/featured/InputPrompt.tsx
  apps/app/components/welcome/featured/MobileInputPrompt.tsx
  apps/app/hooks/useDreamshaper.tsx
  apps/app/hooks/usePromptVersionStore.ts
Labels: Review effort 2/5

#544 Update Discord URL again
  apps/app/app/(main)/Header.tsx
  apps/app/components/header/index.tsx
  apps/app/components/modals/capacity-notification-modal.tsx
  apps/app/components/modals/trial-expired-modal.tsx
  apps/app/components/modals/unified-signup-modal.tsx
  apps/app/components/welcome/featured/Header.tsx
  apps/app/components/welcome/featured/PlayerOverlay.tsx
  apps/app/components/welcome/featured/index.tsx
  apps/app/components/welcome/index.tsx
Labels: Review effort 2/5

#532 feat: handle media and login behavior in in-app browsers
  apps/app/app/(main)/MainLayoutClient.tsx
  apps/app/app/(main)/OptimizedVideo.tsx
  apps/app/app/(main)/TikTokBrowserWarning.tsx
  apps/app/app/create/TikTokFallback.tsx
  apps/app/app/create/page.tsx
  apps/app/app/whoami/page.tsx
  apps/app/components/daydream/LoginScreen/DiscordLoginButton.tsx
  apps/app/components/daydream/LoginScreen/GoogleLoginButton.tsx
  apps/app/components/daydream/LoginScreen/index.tsx
  apps/app/hooks/usIsMobileInAppBrowser.ts
  apps/app/hooks/useIsTikTokBrowser.ts
  apps/app/lib/userAgentIdentify.ts
Labels: Review effort 3/5

#546 fix: guest user redirected to onboarding flow for existing acc
  apps/app/components/daydream/WelcomeScreen/Personas.tsx
  apps/app/components/daydream/index.tsx
Labels: Review effort 2/5

#557 feat: redirect socials paths to base route
  apps/app/next.config.mjs
Labels: Review effort 1/5

#556 fix: allow create CTA for guest mode
  apps/app/app/(main)/Header.tsx
  apps/app/components/daydream/index.tsx
Labels: Review effort 2/5

#559 pnpm version bump in Github Actions
  .github/workflows/e2e-monitor.yml
  .github/workflows/e2e-test.yml
  .github/workflows/validate-code.yml
Labels: Review effort 1/5

#560 fix: reset guest user state to allow sign up
  apps/app/components/modals/unified-signup-modal.tsx
Labels: Review effort 2/5

#565 Remove horizontal separators on clipping modal
  apps/app/components/daydream/Clipping/ClipOptionsModal.tsx
Labels: Review effort 1/5

#566 feat: conditionally render Dreamshaper content
  apps/app/components/welcome/featured/Dreamshaper.tsx
  apps/app/components/welcome/featured/TutorialVideo.tsx
Labels: Review effort 2/5

#567 feat: align overlay state with actual playback state
  apps/app/components/welcome/featured/Dreamshaper.tsx
  apps/app/components/welcome/featured/MainContent.tsx
  apps/app/components/welcome/featured/Overlay.tsx
  apps/app/components/welcome/featured/player.tsx
  apps/app/hooks/useStreamStatus.ts
Labels: Review effort 1/5

#568 fix: reset state on mount
  apps/app/components/welcome/featured/MainContent.tsx
  apps/app/components/welcome/featured/player.tsx
  apps/app/hooks/useStreamStatus.ts
Labels: Review effort 2/5

#577 feat: update navigation methods
  apps/app/app/(main)/OptimizedVideo.tsx
  apps/app/hooks/useDreamshaper.tsx
  apps/app/hooks/usePromptStore.ts
Labels: Review effort 2/5

#579 perf: update playback state handling
  apps/app/components/welcome/featured/Dreamshaper.tsx
  apps/app/components/welcome/featured/Header.tsx
  apps/app/components/welcome/featured/MainContent.tsx
  apps/app/components/welcome/featured/player.tsx
  apps/app/hooks/useDreamshaper.tsx
Labels: Review effort 3/5

#572 fix: Improve Twitter preview video
  apps/app/app/embed/clips/[slug]/page.tsx
Labels: Review effort 1/5

#571 fix: hide create clip CTA before stream goes live (guest mode)
  apps/app/components/header/user.tsx
  apps/app/components/welcome/featured/Header.tsx
Labels: Review effort 2/5

#548 feat: fetch playback url from whip response
  apps/app/app/ServiceWorker.tsx
  apps/app/app/layout.tsx
  apps/app/components/welcome/featured/player.tsx
  apps/app/hooks/usePlaybackUrlStore.ts
  apps/app/public/sw.js
Labels: Review effort 4/5

#587 perf: mock HEAD requests to /whip
  apps/app/public/sw.js
Labels: Review effort 2/5

#552 fix: made prompt to be editable directly without resetting
  apps/app/components/welcome/featured/InputPrompt.tsx
  apps/app/components/welcome/featured/MobileInputPrompt.tsx
Labels: Review effort 3/5

#589 fix: align items in prompts sidebar
  apps/app/components/welcome/featured/BentoGridOverlay.tsx
Labels: Review effort 1/5

#591 fix: alignment of actions and banner
  apps/app/components/welcome/featured/Dreamshaper.tsx
  apps/app/components/welcome/featured/Header.tsx
Labels: Review effort 2/5

#592 CTAs
  apps/app/app/(main)/page.tsx
Labels: Review effort 2/5

#590 Hth tracking
  apps/app/app/(main)/page.tsx
  apps/app/components/home/ActionButton.tsx
  apps/app/components/home/PromptPanel.tsx
Labels: Review effort 2/5

#594 dd: feat: landing ui overhaul + retries + recover from default prompt
  apps/app/app/(main)/page.tsx
  apps/app/app/api/prompts/store.ts
  apps/app/app/layout.tsx
  apps/app/components/ConditionalIntercom.tsx
  apps/app/components/home/ActionButton.tsx
  apps/app/components/home/CloudBackground.tsx
  apps/app/components/home/LivepeerPlayer.tsx
  apps/app/components/home/PromptDisplay.tsx
  apps/app/components/home/PromptForm.tsx
  apps/app/components/home/PromptPanel.tsx
  apps/app/components/home/VideoSection.tsx
  apps/app/hooks/useThrottledInput.ts
  apps/app/lib/db/services/prompt-queue.ts
  apps/app/lib/livepeer.ts
Labels: Review effort 4/5

#598 feat: add fallback behavior when no playback url header
  apps/app/app/ServiceWorker.tsx
  apps/app/components/welcome/featured/player.tsx
  apps/app/hooks/usePlaybackUrlStore.ts
  apps/app/public/sw.js
Labels: Review effort 3/5

#581 Track TikTok fallback and link copy
  apps/app/app/create/TikTokFallback.tsx
  apps/app/app/create/page.tsx
Labels: Review effort 2/5

#599 fix: track playing state for videoJS player
  apps/app/components/welcome/featured/player.tsx
  apps/app/components/welcome/featured/videojs-player.tsx
Labels: Review effort 2/5

#600 fix: broken layout for videoJS player
  apps/app/components/welcome/featured/videojs-player.tsx
Labels: Review effort 2/5

#595 My Clips
  apps/app/app/api/clips/user/route.ts
  apps/app/components/daydream/Clipping/ClipButton.tsx
  apps/app/components/daydream/Clipping/ClipSummaryContent.tsx
  apps/app/components/welcome/featured/BentoGridOverlay.tsx
Labels: Review effort 4/5

#597 dd: landing: Hero
  apps/app/app/(main)/page.tsx
  apps/app/components/home/Footer.tsx
  apps/app/components/home/HeroSection.tsx
  apps/app/components/home/PromptForm.tsx
  apps/app/components/home/PromptPanel.tsx
  apps/app/components/home/VideoSection.tsx
  apps/app/package.json
  apps/app/tailwind.config.ts
  pnpm-lock.yaml
Labels: Review effort 3/5

#608 Switch to using a Prod post-transformation video stream
  apps/app/components/home/HeroSection.tsx
  apps/app/components/home/VideoSection.tsx
Labels: Review effort 2/5

#607 fix: Create env vars for stream settings
  apps/app/.env.example
  apps/app/app/api/prompts/store.ts
  apps/app/components/home/VideoSection.tsx
Labels: Review effort 2/5

#609 dd: feat: mobile layout for landing
  apps/app/app/(main)/page.tsx
  apps/app/app/api/prompts/store.ts
  apps/app/components/home/Footer.tsx
  apps/app/components/home/PromptDisplay.tsx
  apps/app/components/home/PromptForm.tsx
  apps/app/components/home/PromptPanel.tsx
  apps/app/components/home/VideoSection.tsx
Labels: Review effort 4/5

#615 dd: disable audio (revert this when infra ready)
  apps/app/components/playground/broadcast.tsx
Labels: Review effort 2/5

#619 fix: broken multiplayer stream links and vercel env vars
  apps/app/components/home/HeroSection.tsx
  apps/app/components/home/VideoSection.tsx
Labels: Review effort 2/5

#612 perf: enable noICEGathering flag
  apps/app/components/playground/broadcast.tsx
Labels: Review effort 1/5

#623 fix: remove duplicate fullscreen control causing confusion
  apps/app/components/welcome/featured/player.tsx
Labels: Review effort 2/5

#633 Don't show trending styles that don't have thumbnails
  apps/app/app/api/clips/route.ts
Labels: Review effort 2/5

#631 fix: move clips page overlay to display over multiplayer
  apps/app/app/(main)/MultiplayerHomepage.tsx
  apps/app/app/(main)/QuickviewVideo.tsx
  apps/app/app/(main)/layout.tsx
  apps/app/app/(main)/page.tsx
Labels: Review effort 3/5

#635 Order admin page in same way as site. Try to fix issue with Admin updates not persisting to DB.
  apps/app/app/api/admin/clips/route.ts
  apps/app/app/api/admin/clips/update/route.ts
Labels: Review effort 3/5

#634 fix: allow creation of multiple streams
  apps/app/app/(main)/OptimizedVideo.tsx
  apps/app/components/welcome/featured/player.tsx
  apps/app/package.json
  pnpm-lock.yaml
Labels: Review effort 3/5

#637 NSFW Prompt Filter
  apps/app/app/api/prompts/route.ts
  apps/app/hooks/usePromptsApi.ts
  apps/app/lib/nsfwCheck.test.ts
  apps/app/lib/nsfwCheck.ts
  apps/app/package.json
  pnpm-lock.yaml
Labels: Review effort 3/5

#638 Move tracking into existing event
  apps/app/app/(main)/MultiplayerHomepage.tsx
  apps/app/app/api/prompts/route.ts
  apps/app/hooks/usePromptsApi.ts
Labels: Review effort 2/5

#642 feat: skip HEAD call for WHEP
  apps/app/public/sw.js
Labels: Review effort 3/5

#643 fix: stream not playing on staging
  apps/app/app/ServiceWorker.tsx
  apps/app/public/sw.js
Labels: Review effort 1/5

#650 fix: source url for staging streams
  apps/app/components/home/VideoSection.tsx
Labels: Review effort 2/5

#645 Revert "dd: disable audio (revert this when infra ready) (#615)"
  apps/app/components/playground/broadcast.tsx
Labels: Review effort 2/5

#666 fix: dreamshaper related hardcode
  apps/app/hooks/useDreamshaper.tsx
Labels: Review effort 2/5

#664 test: enable queryparams for APP_URL
  apps/app-e2e/playwright.config.ts
  apps/app-e2e/tests/common.ts
Labels: Review effort 2/5

#671 Fix prompt list only showing oldest prompts on mobile
  apps/app/components/home/PromptDisplay.tsx
Labels: Review effort 2/5

#672 Display mobile prompt immediately after submitting
  apps/app/components/home/PromptDisplay.tsx
Labels: Review effort 2/5

#679 Anchor link for multiplayer viewport
  apps/app/app/(main)/MultiplayerHomepage.tsx
  apps/app/components/home/HeroSection.tsx
Labels: Review effort 2/5

#681 Multiplayer Selection of Video Streams
  apps/app/components/home/HeroSection.tsx
  apps/app/components/home/VideoSection.tsx
Labels: Review effort 3/5

#692 Fail workflow on flaky tests
  .github/workflows/e2e-monitor.yml
Labels: Review effort 1/5

#691 feat: enable audio
  apps/app/app/api/admin/notifications/discord/route.ts
  apps/app/components/playground/broadcast.tsx
Labels: Review effort 1/5

#669 E2E improvements
  .github/workflows/e2e-monitor.yml
  apps/app-e2e/playwright.config.ts
  apps/app-e2e/tests/common.ts
  apps/app-e2e/tests/video.spec.ts
Labels: Review effort 3/5

#694 feat: enhance prompt application to support multiple target streams
  apps/app/app/api/prompts/store.ts
Labels: Review effort 3/5

#695 Add 'trending' prompts
  apps/app/components/home/PromptPanel.tsx
Labels: Review effort 3/5

#686 Reproducible Youtube Restream Flow
  .github/workflows/deploy-restreamers.yml
  apps/restreamers/Dockerfile
  apps/restreamers/deploy.sh
  apps/restreamers/fly.toml
  apps/restreamers/restream-lp-to-dd.sh
  apps/restreamers/restream-yt-to-lp.sh
Labels: Review effort 3/5

#697 ci: change restreamer deploy trigger conditions
  .github/workflows/deploy.restreamers.staging.yml
  apps/restreamers/Dockerfile
  apps/restreamers/deploy.local.sh
  apps/restreamers/fly.toml
  apps/restreamers/restream-lp-to-dd.sh
  apps/restreamers/restream-yt-to-lp.sh
Labels: Review effort 2/5

#689 feat: polish multiplayer mobile experience
  apps/app/app/(main)/MultiplayerHomepage.tsx
  apps/app/components/home/Footer.tsx
  apps/app/components/home/HeaderSection.tsx
  apps/app/components/home/PromptDisplay.tsx
  apps/app/components/home/PromptForm.tsx
  apps/app/components/home/PromptPanel.tsx
  apps/app/components/home/VideoSection.tsx
  packages/design-system/styles/globals.css
Labels: Review effort 4/5

#701 fix: simplify ffmpeg servers
  apps/restreamers/restream-lp-to-dd.sh
  apps/restreamers/restream-yt-to-lp.sh
Labels: Review effort 2/5

#706 feat: encode stream on the fly
  .github/workflows/deploy.restreamers.staging.yml
  apps/restreamers/fly.toml
  apps/restreamers/restream-lp-to-dd.sh
  apps/restreamers/restream-yt-to-lp.sh
Labels: Review effort 2/5

#711 feat: change restreamer deployment strategy
  apps/restreamers/fly.toml
Labels: Review effort 1/5

#708 fix: ignore decoding timestamp
  apps/restreamers/restream-yt-to-lp.sh
Labels: Review effort 1/5

#717 fix: footer padding fix on prompt panel
  apps/app/components/home/PromptForm.tsx
Labels: Review effort 1/5

#731 fix: stream controls vertical scroll
  apps/app/components/home/VideoSection.tsx
Labels: Review effort 1/5

#732 Just check the maximum frame difference
  apps/app-e2e/tests/common.ts
Labels: Review effort 2/5

#733 prompt_text -> prompt in metric property for consistency
  apps/app/components/home/PromptPanel.tsx
Labels: Review effort 2/5
